### PR TITLE
Replace SnowTrace with SnowScan.xyz a product of Etherscan

### PR DESCRIPTION
**Pull request by JazzBashara**
Replace SnowTrace with SnowScan.xyz a product of Etherscan. Overall a better working product to have as the default Avalanche c-chain block explorer.

---

## PR-Codex overview
The focus of this PR is to update the Avalanche explorer to snowscan.xyz, replacing snowtrace.io.

### Detailed summary
- Updated the Avalanche explorer from SnowTrace to SnowScan with new URLs.
- Utilizes snowscan.xyz for blockchain exploration and API calls.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by jxom** [comment]
Where can I find proof that Snowscan was built by Etherscan?

**Comment by JazzBashara** [comment]
> Where can I find proof that Snowscan was built by Etherscan?

Avalanche Vice President Tweeted it out.

https://x.com/luigidemeo/status/1759639023188955248?s=46&t=GsjapP52zCQvlypngdTIvw

Also on the Etherscan website:

https://kbadm.etherscan.com/what-is-snowscan/

**Comment by jxom** [comment]
Thanks!

**Comment by vittominacori** [comment]
@jxom @JazzBashara they first announced that this instance would be [discontinued](https://twitter.com/SnowScanHQ/status/1718982848462696919) then they changed the name to `SnowScan` but there are no new announcements on their Twitter profile.

Is that a maintained explorer or not?

**Pull request merged**
