### PR TITLE
Sei

### PR DESCRIPTION
**Pull request by abs3ntdev**
### Description

Add sei chain

---

## PR-Codex overview
This PR adds a new chain called `Sei` with its definitions, including RPC URLs, block explorers, and contracts.

### Detailed summary
- Added `sei` chain definition
- Defined `sei` chain with ID, name, native currency, RPC URLs, block explorers, and contracts

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by jxom** [comment]
Please re-open this PR when this chain is merged into https://github.com/ethereum-lists/chains.

**Comment by tiagofilipenunes** [comment]
@abs3ntdev 

Btw Multicall3 now has an official deployment https://github.com/mds1/multicall/issues/269 at the standard address 0xcA11bde05977b3631167028862bE2a173976CA11

Can check it in https://www.multicall3.com/deployments

**Comment by abs3ntdev** [comment]
> @abs3ntdev
> 
> Btw Multicall3 now has an official deployment [mds1/multicall#269](https://github.com/mds1/multicall/issues/269) at the standard address 0xcA11bde05977b3631167028862bE2a173976CA11
> 
> Can check it in https://www.multicall3.com/deployments

thank you. ive updated it on my fork. just waiting on ethereum-lists pr to merge to reopen

**Comment by tiagofilipenunes** [comment]
@abs3ntdev https://github.com/ethereum-lists/chains/pull/5157 has been merged

**Pull request closed without merging**
