### PR TITLE
fix: rename zkSync to ZKsync

### PR DESCRIPTION
**Pull request by JackHamer09**
- Renamed zkSync to ZKsync
  - Context: zkSync was officially renamed to ZKsync a while ago
  - Variable names: `zkSync` -> `zksync` (for simplicity and consistency between folder/file names and variables)
  - Types: `ZkSync` -> `Zksync`
- Fixed few incorrect imports and examples in documentation
- Removed deprecated `zkSyncTestnet` chain

This creates a minor breaking change because of changed variable and type names.

---

## PR-Codex overview
This PR focuses on renaming `zkSync` to `ZKsync`, updating variable names, types, and removing `zkSyncTestnet`. 

### Detailed summary
- Renamed `zkSync` to `ZKsync` for consistency
- Updated variable names and types to `zksync`
- Removed `zkSyncTestnet` chain
- Updated imports and references to `zksync`

> The following files were skipped due to too many changes: `site/pages/zksync/actions/signTransaction.md`, `src/zksync/actions/getTestnetPaymasterAddress.test.ts`, `src/README.md`, `src/zksync/types/fee.ts`, `src/zksync/actions/estimateFee.test.ts`, `src/zksync/actions/getAllBalances.test.ts`, `src/zksync/decorators/publicL2.test.ts`, `src/zksync/utils/assertEip712Request.ts`, `src/zksync/actions/estimateGasL1ToL2.test.ts`, `test/src/zksync.ts`, `src/zksync/actions/getL1ChainId.ts`, `src/actions/public/verifyHash.test.ts`, `src/zksync/actions/getL1BatchNumber.ts`, `test/src/anvil.ts`, `src/zksync/actions/getLogProof.ts`, `src/zksync/actions/getBaseTokenL1Address.ts`, `src/zksync/actions/getMainContractAddress.ts`, `src/chains/definitions/zkSyncLocalNode.ts`, `src/chains/definitions/zkSyncInMemoryNode.ts`, `src/zksync/actions/getBridgehubContractAddress.ts`, `src/zksync/actions/getTestnetPaymasterAddress.ts`, `src/zksync/actions/getAllBalances.ts`, `src/zksync/actions/getL1BatchBlockRange.ts`, `src/zksync/utils/assertEip712Transaction.ts`, `src/zksync/actions/getDefaultBridgeAddresses.ts`, `src/zksync/actions/estimateGasL1ToL2.ts`, `src/zksync/actions/signEip712Transaction.test.ts`, `src/zksync/actions/deployContract.test.ts`, `src/chains/definitions/zkSync.ts`, `site/pages/zksync/actions/getMainContractAddress.md`, `src/zksync/actions/sendEip712Transaction.ts`, `src/zksync/types/chain.ts`, `src/zksync/actions/sendTransaction.ts`, `src/zksync/actions/getBlockDetails.ts`, `src/zksync/actions/signTransaction.ts`, `src/zksync/actions/getL1BatchDetails.ts`, `src/zksync/actions/signEip712Transaction.ts`, `src/zksync/actions/signTransaction.test.ts`, `site/pages/zksync/actions/getBlockDetails.md`, `src/zksync/actions/getTransactionDetails.ts`, `site/pages/zksync/chains.md`, `src/zksync/types/eip712.ts`, `site/pages/zksync/actions/getDefaultBridgeAddress.md`, `src/zksync/actions/estimateFee.ts`, `src/chains/definitions/zkSyncSepoliaTestnet.ts`, `src/zksync/utils/getEip712Domain.ts`, `src/zksync/actions/getRawBlockTransactions.ts`, `site/pages/zksync/client.md`, `src/zksync/actions/sendTransaction.test.ts`, `src/zksync/types/log.ts`, `src/zksync/serializers.ts`, `src/zksync/utils/getEip712Domain.test.ts`, `src/zksync/actions/sendEip712Transaction.test.ts`, `src/actions/public/getTransactionReceipt.test.ts`, `src/zksync/types/eip1193.ts`, `site/pages/docs/chains/zksync.md`, `src/zksync/index.ts`, `src/zksync/types/block.ts`, `src/zksync/formatters.test.ts`, `site/pages/zksync.mdx`, `src/zksync/decorators/eip712.test.ts`, `src/chains/index.ts`, `src/zksync/decorators/eip712.ts`, `src/zksync/formatters.ts`, `src/zksync/formatters.test-d.ts`, `src/zksync/serializers.test.ts`, `src/zksync/decorators/publicL2.ts`, `src/zksync/types/transaction.ts`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by JackHamer09** [comment]
Not sure why test fail...

**Review by tmm — COMMENTED** [review]
In addition to the new imports, let's keep the old imports and add a `@deprecated` comment to them.

**Comment by JackHamer09** [comment]
@tmm added all old imports back with `@deprecated` jsdoc

**Comment by tmm** [comment]
Wasn't able to push. Closing in favor of https://github.com/wevm/viem/pull/2586

**Pull request closed without merging**
