### PR TITLE
🐛 utils: fix strict address check

### PR DESCRIPTION
**Pull request by cruzdanilo**
# issue

`isAddress` strict check is skipped when the input is an address entirely lowercase.

# solution

remove lowercase comparison.

# impact

although this fix doesn't change the _expected_ result, it is actually a breaking change for many projects (and many tests in this project), so i will leave the decision to the core maintainers.

---

## PR-Codex overview
This PR updates the `isAddress` utility function to handle case sensitivity and strict mode for Ethereum addresses.

### Detailed summary
- Fixed case sensitivity check in `isAddress` function
- Added strict mode option to `isAddress` function
- Updated test cases for `isAddress` function to reflect changes

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by iosh** [comment]
As you said, this will be a big change, maybe we can add some comments or document to this function to tell user that lowercase address will not be checksum check and return true

**Comment by jxom** [comment]
The behavior we have now is expected. The strict behavior checks for casing mismatches in the checksum (ie. end user may not encounter a memory bit flip, or type an incorrect character) and not the fully lowercased address. Maybe we should document it better.

**Comment by cruzdanilo** [comment]
how should we check if a `0x{string}` is a checksummed address?

**Comment by iosh** [comment]
> how should we check if a `0x{string}` is a checksummed address?

How about this
```ts
import { checksumAddress } from "viem";
const addr = '0x....'
const isChecksumAddress = checksumAddress(addr) === addr;
```

**Pull request closed without merging**
