### PR TITLE
Add ENS registry and universal resolver for JBC chain

### PR DESCRIPTION
**Pull request by leojid**
## PR-Codex overview
This PR focuses on adding addresses and block creation information for `ensRegistry` and `ensUniversalResolver` in the `jbc.ts` file.

### Detailed summary
- Added `ensRegistry` object with address and block creation information.
- Added `ensUniversalResolver` object with address and block creation information.
- Updated the `testnet` flag to `false`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by leojid** [comment]
Jibchain official website: https://jibchain.net/
JIB ID website : https://jibid.xyz/
ETHRegistrarController: https://exp-l1.jibchain.net/address/0xaB630401491EAe6B2967D49A78837F99EE93E4f7

**Review by jxom — COMMENTED** [review]
Are there any links to prove that these addresses are the official ones?

**Comment by leojid** [comment]
Hi @jxom ,

You may verify our affiliation with the Jibchain ecosystem by visiting their official website.

Screenshot 2024-01-24 at 10 20 49

**Comment by leojid** [comment]
@jxom another proof: https://twitter.com/jibchain/status/1750013877507731651

**Comment by leojid** [comment]
@jxom Hi, Any news regarding this PR?

**Comment by jxom** [comment]
Hi. We only accept official ENS addresses listed here: https://docs.ens.domains/learn/deployments

**Pull request closed without merging**
