### PR TITLE
Added Edgeless Chain

### PR DESCRIPTION
**Pull request by edgeless-network**
## PR-Codex overview
This PR adds support for Edgeless Network and Edgeless Testnet to the project.

### Detailed summary
- Added `edgeless` and `edgelessTestnet` chains to `index.ts`
- Defined `edgeless` chain with specific details in `edgeless.ts`
- Defined `edgelessTestnet` chain with specific details in `edgelessTestnet.ts`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by jxom — COMMENTED** [review]
Will merge this once https://github.com/ethereum-lists/chains/pull/4621 is merged.

**Comment by jxom** [comment]
Can you please reopen this PR when https://github.com/ethereum-lists/chains/pull/4621 is merged? It'll be easier to remind me to merge this! 

Thanks!

**Comment by edgeless-network** [comment]
@jxom Can we merge it even if the https://github.com/ethereum-lists/chains/pull/4621 is not yet merged? It's been two weeks and we don't know anyone with merging abilities from that repo and they haven't reviewed it at all

**Comment by jxom** [comment]
Unfortunately not as there could be chain id conflict in the future.

**Comment by edgeless-network** [comment]
Do you know anyone that could help with that repo?

**Pull request closed without merging**
