### PR TITLE
feat: add multicall address for degen chain

### PR DESCRIPTION
**Pull request by joeblau**
Add multicall3 address to support viem multicall

Contract on degen block explorer:  https://explorer.degen.tips/address/0xcA11bde05977b3631167028862bE2a173976CA11

---

## PR-Codex overview
This PR updates the `address` and `blockCreated` values for the `multicall3` contract in `degen.ts`.

### Detailed summary
- Updated `address` for `multicall3` contract to '0xcA11bde05977b3631167028862bE2a173976CA11'
- Updated `blockCreated` for `multicall3` contract to 142

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by joeblau** [comment]
There's a problem with this right now. The `aggregate3` method can't be found on the contract

```
This could be due to any of the following:
      - The contract does not have the function "aggregate3",
      - The parameters passed to the contract function may be invalid, or
      - The address is not a contract.
     
    Contract Call:
      address:   0xca11bde05977b3631167028862be2a173976ca11
      function:  aggregate3((address target, bool allowFailure, bytes callData)[])
      args:                ([{"allowFailure":true,"callData":"0x06fdde03","target":"0x54f667dB585b7B10347429C72c36c8B59aB441cb"},{"allowFailure":true,"callData":"0x95d89b41","target":"0x54f667dB585b7B10347429C72c36c8B59aB441cb"},{"allowFailure":true,"callData":"0x313ce567","target":"0x54f667dB585b7B10347429C72c36c8B59aB441cb"}])
```

Doing some more investigation.

**Comment by joeblau** [comment]
This update is dependent on https://github.com/mds1/multicall/issues/244

**Comment by jxom** [comment]
Can you reopen this when it is deployed?

**Comment by joeblau** [comment]
Will do

**Pull request closed without merging**
